language: d
sudo: false
install:
  - mkdir bin

script:
  - dub test
  - dub run --build=unittest -c ut

matrix:
    include:
        - d: dmd
        - d: dmd-2.073.2
        - d: dmd-2.072.2
        - d: dmd-2.071.2
        - d: dmd-2.070.2
        - d: ldc
